# Generated by SmokeHarvest - DO NOT EDIT MANUALLY
# Baseline captured: 2025-01-28T10:30:00Z
# Config: examples/httpbin/smokeharvest.config.yaml

import re

import pytest
from playwright.sync_api import Page, expect


class TestHttpbinFormSubmission:
    """Test the pizza order form at httpbin.org/forms/post"""

    def test_submits_pizza_order_form_and_verifies_response(self, page: Page):
        # Navigate to form
        page.goto("https://httpbin.org/forms/post")
        expect(page).to_have_title(re.compile(r"httpbin", re.IGNORECASE))

        # Fill customer information
        page.fill('input[name="custname"]', "Test Customer")
        page.fill('input[name="custtel"]', "555-1234")
        page.fill('input[name="custemail"]', "test@example.com")

        # Select pizza size
        page.check('input[name="size"][value="medium"]')

        # Select toppings
        page.check('input[name="topping"][value="bacon"]')
        page.check('input[name="topping"][value="cheese"]')

        # Set delivery time
        page.fill('input[name="delivery"]', "12:00")

        # Add comments
        page.fill('textarea[name="comments"]', "Ring doorbell twice")

        # Submit form
        page.click('button[type="submit"]')

        # Verify response contains submitted data
        body = page.locator("body")
        expect(body).to_contain_text("Test Customer")
        expect(body).to_contain_text("555-1234")
        expect(body).to_contain_text("medium")
        expect(body).to_contain_text("bacon")
        expect(body).to_contain_text("cheese")
        expect(body).to_contain_text("12:00")
        expect(body).to_contain_text("Ring doorbell twice")
